#!/bin/bash

echo "🚀 BountyChain Frontend Test"
echo "============================"
echo ""

# Dev server'ı başlat
echo "Starting dev server..."
npm run dev &
DEV_PID=$!

echo "Dev server started (PID: $DEV_PID)"
echo ""
echo "⏳ Waiting 3 seconds for server to be ready..."
sleep 3

echo ""
echo "✅ Frontend is running at: http://localhost:5174"
echo ""
echo "===================="
echo "📝 MANUAL TEST STEPS"
echo "===================="
echo ""
echo "1. WALLET CONNECTION TEST"
echo "   □ Click 'Connect Wallet' button"
echo "   □ Select Sui Wallet"
echo "   □ Approve connection"
echo "   □ Check if address appears in header"
echo "   Expected: ✅ Wallet connected, address shown"
echo ""

echo "2. HOMEPAGE TEST"
echo "   □ Check if stats are visible (TVL, Total Bounties, etc.)"
echo "   □ All navigation links work"
echo "   □ Footer links work"
echo "   Expected: ✅ All elements render correctly"
echo ""

echo "3. HACK LIST TEST"
echo "   □ Navigate to Hack List page"
echo "   □ Check if bounties load (may be empty)"
echo "   □ Try filter buttons (All, Active, Expired)"
echo "   □ Try difficulty filter"
echo "   □ Try sort dropdown"
echo "   Expected: ✅ Filters work, no console errors"
echo ""

echo "4. CREATE BOUNTY TEST"
echo "   □ Navigate to Create Bounty page"
echo "   □ Fill all required fields:"
echo "      - Project Name: 'Test Project'"
echo "      - Title: 'Test Bug Bounty'"
echo "      - Description: 'Testing bounty creation'"
echo "      - Scope: 'Smart contracts only'"
echo "      - Rewards: Critical=1, High=0.5, Medium=0.2, Low=0.1 SUI"
echo "      - Deadline: 7 days"
echo "      - GitHub URL: https://github.com/test/test"
echo "      - Website: https://test.com"
echo "   □ Click 'Create Bounty & Lock Funds'"
echo "   □ Sign transaction in wallet"
echo "   □ Wait for confirmation"
echo "   Expected: ✅ Transaction succeeds, bounty created"
echo ""

echo "5. POC SUBMISSION TEST (after creating bounty)"
echo "   □ Go back to Hack List"
echo "   □ Click on your test bounty"
echo "   □ Click 'Submit PoC'"
echo "   □ Select a test file (any .txt or .pdf)"
echo "   □ Choose severity (e.g., High)"
echo "   □ Write vulnerability description"
echo "   □ (Optional) Enable Seal Encryption"
echo "   □ Click 'Upload & Submit'"
echo "   □ Watch progress bar"
echo "   □ Sign transaction"
echo "   Expected: ✅ File uploads to Walrus, transaction succeeds"
echo ""

echo "6. MINI HACK TEST"
echo "   □ Navigate to Mini Hack page"
echo "   □ Check if challenges are visible"
echo "   □ Click 'Submit Solution' on any challenge"
echo "   □ Enter test solution: 'test123'"
echo "   □ Click 'Submit Solution'"
echo "   □ Sign transaction"
echo "   Expected: ⚠️  Will fail (wrong answer) but transaction should work"
echo ""

echo "7. LEADERBOARD TEST"
echo "   □ Navigate to Leaderboard page"
echo "   □ Check if leaderboard loads"
echo "   □ Your address should appear if you earned points"
echo "   Expected: ✅ Leaderboard displays, no errors"
echo ""

echo "========================"
echo "🐛 COMMON ERRORS TO CHECK"
echo "========================"
echo ""
echo "In Browser Console (F12 → Console):"
echo "   ❌ 'Failed to fetch' → Check Walrus endpoints"
echo "   ❌ 'Transaction failed' → Check gas balance"
echo "   ❌ 'Object not found' → Check .env IDs"
echo "   ❌ 'CORS error' → Normal for Walrus, handled in code"
echo ""

echo "In Network Tab (F12 → Network):"
echo "   ✅ Walrus uploads: Status 200"
echo "   ✅ Sui RPC calls: Status 200"
echo "   ⚠️  Walrus 404 before upload: Normal"
echo ""

echo "Wallet Issues:"
echo "   ❌ 'Insufficient gas' → Get testnet SUI from faucet"
echo "   ❌ 'Network mismatch' → Switch wallet to testnet"
echo "   ❌ 'Transaction rejected' → Check wallet balance"
echo ""

echo "================================"
echo "🎯 WHAT YOU'RE LOOKING FOR"
echo "================================"
echo ""
echo "✅ GOOD SIGNS:"
echo "   • Wallet connects successfully"
echo "   • No red errors in console"
echo "   • Forms validate correctly"
echo "   • Transactions get signed"
echo "   • Success notifications appear"
echo "   • File uploads show progress"
echo ""

echo "❌ BAD SIGNS:"
echo "   • Console full of red errors"
echo "   • Wallet doesn't connect"
echo "   • Buttons don't respond"
echo "   • Forms submit without validation"
echo "   • Transactions fail silently"
echo "   • Infinite loading states"
echo ""

echo "========================================="
echo "📊 AFTER TESTING, REPORT THESE:"
echo "========================================="
echo "1. Which tests passed? ✅"
echo "2. Which tests failed? ❌"
echo "3. Any console errors? (copy-paste)"
echo "4. Screenshots of issues"
echo "5. What you expected vs what happened"
echo ""

echo "Press Ctrl+C to stop the dev server when done testing."
echo ""

# Keep script running
wait $DEV_PID
